name: analyzer_cli
version: 1.1.1
author: Dart Team <misc@dartlang.org>
description: Command line interface for the Dart Analyzer.
homepage: https://github.com/dart-lang/analyzer_cli
environment:
  sdk: '>=1.8.0 <2.0.0'
dependencies:
  analyzer: ^0.26.0+6
  args: ^0.13.0
  cli_util: ^0.0.1
  dev_compiler: ^0.1.1
  linter: ^0.1.3
  package_config: ^0.1.1
  plugin: ^0.1.0
  yaml: ^2.1.2
dev_dependencies:
  mockito: ^0.8.2
  test: ^0.12.0
